### ISSUE TITLE
Temperature display for FreeBSD

### ISSUE THREAD

**Issue by schijtreiger** [MeFri/lcdproc-temperature#1]
Howdy,
Hopefully this message gets to you even though your repo appears to be dormant for some years now. 
You've done some great work here aaaaaaand I'd like to see if it possible to integrate/modify this patch for FreeBSD purposes.
I'm not entirely familiar with how Linux/Debian goes about reporting cpu core temperatures...I'm assuming the "/sys/class/thermal/thermal_zone0/temp" file simply contains a number that is expressed as the temperature in Celsius?
FreeBSD reports cpu core temperatures with "sysctl dev.cpu.<ncpu>.temperature: <number> C" . This is given provided that the Kernel module "coretemp.ko" is loaded. We can, for instance, grab that temperature number by executing "exec sysctl -n dev.cpu.0.temperature | cut -c-2" , which gives us a whole number (40) ... "exec sysctl -n dev.cpu.0.temperature | cut -c-4" gives us a number with one decimal (40.1)... "exec sysctl -n dev.cpu.0.temperature | cut -c-5" gives us a number with one decimal and C (C for Celsius)
Full disclosure: I am actually only interested in displaying the temperature, not so much the other very useful gauges you've included in the [Total] screen.
Have you any suggestions/insights in how I might achieve this? Perhaps a modified version of your [Total] screen that is specific to FreeBSD, with say, the cpu core temperatures (individual and/or average of the combined cores) and perhaps along with other temperature sensors on the motherboard? Motherboard temperatures can be provided by executing "sysctl hw.acpi.thermal.tz0.temperature", and for motherboards with multiple temperature sensors on the board, simply executing "sysctl hw.acpi.thermal.tz1.temperature" and so forth. All sysctl commands I listed here do *not* require root/superuser privileges.
I'll be mighty appreciative for any help you can provide!

**Comment by MeFri** [comment]
Hi,
a FreeBSD (Multi-)Temperature screen is a little out of scope for this project. You could write a new screen for lcdproc where you parse the output of your sysctl calls e.g. via popen() and fgets(). Tough it's probably easiest to write a separate, simpler client for that than to go and patch lcdproc itself. You can write a new client for LCDd in python [jinglemansweep/lcdproc](https://github.com/jinglemansweep/lcdproc) or any other language you prefer with much less effort.
